version: "3"
services:
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev    
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      FLASK_ENV: development
